### ISSUE TITLE
Crash with parts interface when server restarts

### ISSUE THREAD

**Issue by SkyDrive94** [ADT-Team-com/AE2-Addition#2]
[12:16:51] [Server thread/ERROR]: [AppEng] Network Event caused exception:
[12:16:51] [Server thread/ERROR]: Offending Class: com.ae.additions.parts.PartUltimateInterface
[12:16:51] [Server thread/ERROR]: Offending Object: com.ae.additions.parts.PartUltimateInterface@33d4d83f
[12:16:51] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@4bccde7e:
java.lang.IllegalStateException: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:171) ~[NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:146) ~[NetworkEventBus$EventMethod.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:192) ~[NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:179) ~[NetworkEventBus$MENetworkEventInfo.class:?]
	at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:101) ~[NetworkEventBus.class:?]
	at appeng.me.Grid.postEvent(Grid.java:223) ~[Grid.class:?]
	at appeng.me.cache.EnergyGridCache.publicPowerState(EnergyGridCache.java:199) ~[EnergyGridCache.class:?]
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:168) ~[EnergyGridCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:286) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:349) ~[TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_210_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252) [FMLCommonHandler.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:163) ~[NetworkEventBus$EventMethod.class:?]
	... 17 more

**Comment by SerStarStory** [comment]
When it crashes? When you place part or open it or maybe during the game load? And how version do you use?

**Comment by SkyDrive94** [comment]
When player tries load chunk with parts after server restart
Thermos-1.7.10-1614

**Comment by SerStarStory** [comment]
Version of the mod

**Comment by SkyDrive94** [comment]
MODID = "ae2additions",
MODNAME = "AE2-Additions",
VERSION = "1.2.1",

**Comment by SerStarStory** [comment]
It's fixed in the latest version for 1.7.10
